### ISSUE TITLE
Example of usage

### ISSUE THREAD

**Issue by earthlingdavey** [lpasselin/tailscale-docker#5]
Hi @lpasselin first off, thank you for sharing this repo and the accompanying article - it for sure helped me with my setup.

I did struggle with one thing though. As a newbie to Tailscale, and not being a networking expert, I didn't really know where to go after installing this repo on 2 machines?

Looking at the simple-example running on 2x machines... How would I access nginxdemos/hello on machine A from machine B?

| Machine | A - nginx host                       | B - client                         |
| ------- | ------------------------------------ | ---------------------------------- |
| Running | simple-example                       | Only tailscale from simple-example |
| Purpose | Expose nginxdemos/hello to tailscale | Access nginxdemos/hello from A     |

I found a working solution with a dependency on [gost](https://github.com/ginuerzh/gost/blob/master/README_en.md). Would you mind taking a look?

Dockerfile for A & B. Copy gost into `usr/bin/gost` with

```
FROM tailscale/tailscale:v1.34.2
COPY start.sh /usr/bin/start.sh
RUN chmod +x /usr/bin/start.sh
COPY --from=chenhw2/gost@sha256:7969a85cc1c89c9b4935dc83ed148ef432861f8ecb48873869c91aac31291c79 /usr/bin/gost /usr/bin/gost
CMD "start.sh"
```

start.sh for A. Forward 55000 to some-service-1

```
# ...
tailscale status
# Use gost to listen on post 55000 and forward to some-service-1 container
gost -L=:55000 -F=some-service-1:55000
wait ${PID}
# ...
```

start.sh for B.

- Add `outbound-http-proxy-listen` on port 1055
- Listen on 52000, forward this first to the outbound-http-proxy-listen
- Then, it has access to tailscale DNS, forward it to machine A

```
# ...
tailscaled --tun=userspace-networking --outbound-http-proxy-listen=localhost:1055 --state=${TAILSCALE_STATE_ARG} &
PID=$!
# ...
tailscale status
# First use the tailscale http proxy, this gets us access to the tailscale DNS
# Then 2nd in the chain is MACHINE_A_URL
gost -L=:52000 -F=http://localhost:1055 -F=${MACHINE_A_URL}
wait ${PID}
# ...
```

docker-compose.yml for B.

```
# ...
  tailscale:
    ports:
      - 52000:52000
    environment:
      MACHINE_A_URL: http://machine-a:55000
# ...
```

When docker-compose is up on both machines. I can run `curl localhost:52000` on B ( the docker host ) and it will request nginxdemos/hello on A and respond from it.

---

This is working for me at the moment.

I suppose my questions are

- Did I make this over engineered?
- Did i miss something obvious, where I don't need to forward ports with gost?

Cheers - Davey

**Comment by ianneub** [comment]
Hi @EarthlingDavey , funny you should post this as I was right in the middle of trying to figure this out myself. Great timing!

I was able to get this working without gost by setting the env variable `HTTP_PROXY=http://localhost:1055/` on machine B as well as adding `--outbound-http-proxy-listen=localhost:1055` to its `start.sh` script. I would think this highly depends on what client software you will be running on machine B, but in my case it worked like a charm.

Prior to setting `--outbound-http-proxy-listen=localhost:1055` in machine B's `start.sh` I could not get access to the service running on machine A.

I hope that helps!

edit: docs from tailscale that led me to setting `HTTP_PROXY`: https://tailscale.com/kb/1112/userspace-networking/#step-2-configure-your-application-to-use-socks5-or-http

edit 2: Sorry, @EarthlingDavey, I just noticed that you were trying to access machine A from the machine B _host_ and not a container in machine B. I misunderstood.

**Comment by ianneub** [comment]
@lpasselin Maybe we could add `--outbound-http-proxy-listen=localhost:1055` to https://github.com/lpasselin/tailscale-docker/blob/45916632fa529b4a83af066cb9050322dd8d6f86/images/tailscale/start.sh#L5 ?

Something like might work:
```
tailscaled --tun=userspace-networking ${TAILSCALE_OPT} --state=${TAILSCALE_STATE_ARG} &
```

**Comment by lpasselin** [comment]
> Did i miss something obvious, where I don't need to forward ports with gost?

It is possible that I misunderstand your issues. But I believe you are missing something important. It is probably because of missing explanations in the readme. Let's fix that.

Here is the typical usage:
On the client machine, you only need the regular tailscale vpn installed and working. _Not in docker_. Just regular tailscale software that can be downloaded from the tailscale website.

Then, you start from one of the examples of this repo and replace the demo service with your own service (to test, you should keep using the nginx/demo, since we know it works). Deploy that like you have done on the server machine.

Finally, (this might be what you are missing) you will look at your tailscale network and notice the new device (which is the container running on the server). This device ip is what you should be using to access the service! So copy paste the ip and type that with the port of your service in a browser. That's it.

Of you course you can chain together many devices and containers open other ports and add tailscale options. But initially that was not the purpose of this simple demo repository.

Let me know if solves the issue!

**Comment by earthlingdavey** [comment]
Hi @ianneub, that's lucky :) Thanks for getting back so quickly.

Ah, I understand more now. And I see how some applications will read the env vars `ALL_PROXY`, `HTTP_PROXY` & `http_proxy`, and that is a general solution that works :)

With that in mind, my suggestion for machine B is very specific to my use case - where in-fact the service on machine A is itself a proxy server (not nginxdemos/hello).

I'm still not sure about one thing though. Did you need gost or some other networking config on A, to allow nginxdemos/hello to be reachable from another tailscale client?

---

Hi @lpasselin thanks for clarifying. I'm getting a better picture now of how to use it. 

Although for my use case I want to have 2 tailscale clients running in non-privileged. Without going too into the weeds, one instance on a k8s cluster (B) and one elsewhere (A).

From your explanation this is the one thing I'm not sure about...

> This device ip is what you should be using to access the service! So copy paste the ip and type that with the port of your service in a browser. That's it.

This is where I got stuck yesterday. I will do further experimenting, but I'm not really sure how in `simple-example` some-service-1 is exposed to the tailscale container.

**Comment by lpasselin** [comment]
@EarthlingDavey this line makes `service-1` network exposed to tailscale container: 
https://github.com/lpasselin/tailscale-docker/blob/45916632fa529b4a83af066cb9050322dd8d6f86/docker-compose/simple-example/docker-compose.yml#L12

**Comment by earthlingdavey** [comment]
@lpasselin oh wow, that's a silly mistake on my part. Soon after cloning the repo I deleted that line during my trail and error ☺️

Thanks again - I think we can close this now :)
